[package]
name = "elio-parser"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
derive_more = { workspace = true, features = ["display"] }
enum-as-inner = { workspace = true }
peg = "0.8.5"
# workspace
either = { workspace = true }
itertools = { workspace = true }

elio-common = { workspace = true }

[dev-dependencies]
insta = { workspace = true, features = ["yaml"] }
