[package]
name = "elio-plannertest"
version.workspace = true
edition.workspace = true

[dependencies]
# elio-catalog = { workspace = true }
elio-common = { workspace = true }
elio-query = { workspace = true }
# elio-cypher = { workspace = true }
# elio-expr = { workspace = true }
elio-parser = { workspace = true }

anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true, features = ["derive", "cargo"] }
itertools = { workspace = true }
sqlplannertest = { workspace = true }
tokio = { workspace = true }

[[test]]
name = "planner_test"
harness = false
