[package]
name = "elio-cypher"
version.workspace = true
edition.workspace = true

[dependencies]
elio-catalog = { workspace = true }
elio-common = { workspace = true }
elio-expr = { workspace = true }
elio-parser = { workspace = true }
elio-storage = { workspace = true }

derive_more = { workspace = true }
educe = { workspace = true, features = ["full"] }
enum-as-inner = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
ordered-float = { workspace = true }
paste = { workspace = true }
pretty-xmlish = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
