[package]
name = "elio-core"
version.workspace = true
edition.workspace = true

[dependencies]
# elio-catalog = { workspace = true }
elio-common = { workspace = true }
elio-query = { workspace = true }
# elio-cypher = { workspace = true }
# elio-exec = { workspace = true }
elio-parser = { workspace = true }
elio-storage = { workspace = true }

# workspace
async-stream = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
# other

uuid = { version = "1.18.1", features = ["v4"] }
