[package]
name = "elio-cmd"
version.workspace = true
edition.workspace = true

[[bin]]
name = "elio"
path = "bin/elio.rs"

[dependencies]
elio-core = { workspace = true }

clap = { workspace = true, features = ["derive", "cargo"] }
dirs = "5"
futures = { workspace = true }
rustyline = "14"
tabled = "0.17"
tikv-jemallocator = { workspace = true }
tokio = { workspace = true }
