[package]
name = "elio-logictest"
version.workspace = true
edition.workspace = true

[dependencies]
elio-common = { workspace = true }
elio-core = { workspace = true }

async-trait = { workspace = true }
datatest-stable = { workspace = true }
futures = { workspace = true }
sqllogictest = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "time"] }

[[test]]
name = "drive"
harness = false
