[package]
name = "elio-expr"
version.workspace = true
edition.workspace = true

[dependencies]
elio-common = { workspace = true }
elio-parser = { workspace = true }

bitvec = { workspace = true }
chrono = { workspace = true }
downcast-rs = { workspace = true }
enum-as-inner = { workspace = true }
expr_macros = { path = "./macros" }
itertools = { workspace = true }
ordered-float = { workspace = true }
thiserror = { workspace = true }
